/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SluzbyRouteImport } from './routes/sluzby'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as NavodyZadaniPlatebniMetodyGoogleAdsAOvereniInzerentaRouteImport } from './routes/navody-zadani-platebni-metody-google-ads-a-overeni-inzerenta'
import { Route as MediestetikRouteImport } from './routes/mediestetik'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SluzbyIndexRouteImport } from './routes/sluzby.index'
import { Route as CaseStudiesIndexRouteImport } from './routes/case-studies.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as SluzbySlugRouteImport } from './routes/sluzby.$slug'
import { Route as CaseStudiesSlugRouteImport } from './routes/case-studies.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as YearMonthDaySlugRouteImport } from './routes/$year.$month.$day.$slug'

const SluzbyRoute = SluzbyRouteImport.update({
  id: '/sluzby',
  path: '/sluzby',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const NavodyZadaniPlatebniMetodyGoogleAdsAOvereniInzerentaRoute =
  NavodyZadaniPlatebniMetodyGoogleAdsAOvereniInzerentaRouteImport.update({
    id: '/navody-zadani-platebni-metody-google-ads-a-overeni-inzerenta',
    path: '/navody-zadani-platebni-metody-google-ads-a-overeni-inzerenta',
    getParentRoute: () => rootRouteImport,
  } as any)
const MediestetikRoute = MediestetikRouteImport.update({
  id: '/mediestetik',
  path: '/mediestetik',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SluzbyIndexRoute = SluzbyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SluzbyRoute,
} as any)
const CaseStudiesIndexRoute = CaseStudiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CaseStudiesRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const SluzbySlugRoute = SluzbySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SluzbyRoute,
} as any)
const CaseStudiesSlugRoute = CaseStudiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CaseStudiesRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const YearMonthDaySlugRoute = YearMonthDaySlugRouteImport.update({
  id: '/$year/$month/$day/$slug',
  path: '/$year/$month/$day/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/mediestetik': typeof MediestetikRoute
  '/navody-zadani-platebni-metody-google-ads-a-overeni-inzerenta': typeof NavodyZadaniPlatebniMetodyGoogleAdsAOvereniInzerentaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sluzby': typeof SluzbyRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/sluzby/$slug': typeof SluzbySlugRoute
  '/blog/': typeof BlogIndexRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
  '/sluzby/': typeof SluzbyIndexRoute
  '/$year/$month/$day/$slug': typeof YearMonthDaySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mediestetik': typeof MediestetikRoute
  '/navody-zadani-platebni-metody-google-ads-a-overeni-inzerenta': typeof NavodyZadaniPlatebniMetodyGoogleAdsAOvereniInzerentaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/sluzby/$slug': typeof SluzbySlugRoute
  '/blog': typeof BlogIndexRoute
  '/case-studies': typeof CaseStudiesIndexRoute
  '/sluzby': typeof SluzbyIndexRoute
  '/$year/$month/$day/$slug': typeof YearMonthDaySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/mediestetik': typeof MediestetikRoute
  '/navody-zadani-platebni-metody-google-ads-a-overeni-inzerenta': typeof NavodyZadaniPlatebniMetodyGoogleAdsAOvereniInzerentaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sluzby': typeof SluzbyRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/sluzby/$slug': typeof SluzbySlugRoute
  '/blog/': typeof BlogIndexRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
  '/sluzby/': typeof SluzbyIndexRoute
  '/$year/$month/$day/$slug': typeof YearMonthDaySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/case-studies'
    | '/mediestetik'
    | '/navody-zadani-platebni-metody-google-ads-a-overeni-inzerenta'
    | '/sitemap.xml'
    | '/sluzby'
    | '/blog/$slug'
    | '/case-studies/$slug'
    | '/sluzby/$slug'
    | '/blog/'
    | '/case-studies/'
    | '/sluzby/'
    | '/$year/$month/$day/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mediestetik'
    | '/navody-zadani-platebni-metody-google-ads-a-overeni-inzerenta'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/case-studies/$slug'
    | '/sluzby/$slug'
    | '/blog'
    | '/case-studies'
    | '/sluzby'
    | '/$year/$month/$day/$slug'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/case-studies'
    | '/mediestetik'
    | '/navody-zadani-platebni-metody-google-ads-a-overeni-inzerenta'
    | '/sitemap.xml'
    | '/sluzby'
    | '/blog/$slug'
    | '/case-studies/$slug'
    | '/sluzby/$slug'
    | '/blog/'
    | '/case-studies/'
    | '/sluzby/'
    | '/$year/$month/$day/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRouteWithChildren
  CaseStudiesRoute: typeof CaseStudiesRouteWithChildren
  MediestetikRoute: typeof MediestetikRoute
  NavodyZadaniPlatebniMetodyGoogleAdsAOvereniInzerentaRoute: typeof NavodyZadaniPlatebniMetodyGoogleAdsAOvereniInzerentaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SluzbyRoute: typeof SluzbyRouteWithChildren
  YearMonthDaySlugRoute: typeof YearMonthDaySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sluzby': {
      id: '/sluzby'
      path: '/sluzby'
      fullPath: '/sluzby'
      preLoaderRoute: typeof SluzbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navody-zadani-platebni-metody-google-ads-a-overeni-inzerenta': {
      id: '/navody-zadani-platebni-metody-google-ads-a-overeni-inzerenta'
      path: '/navody-zadani-platebni-metody-google-ads-a-overeni-inzerenta'
      fullPath: '/navody-zadani-platebni-metody-google-ads-a-overeni-inzerenta'
      preLoaderRoute: typeof NavodyZadaniPlatebniMetodyGoogleAdsAOvereniInzerentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mediestetik': {
      id: '/mediestetik'
      path: '/mediestetik'
      fullPath: '/mediestetik'
      preLoaderRoute: typeof MediestetikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sluzby/': {
      id: '/sluzby/'
      path: '/'
      fullPath: '/sluzby/'
      preLoaderRoute: typeof SluzbyIndexRouteImport
      parentRoute: typeof SluzbyRoute
    }
    '/case-studies/': {
      id: '/case-studies/'
      path: '/'
      fullPath: '/case-studies/'
      preLoaderRoute: typeof CaseStudiesIndexRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/sluzby/$slug': {
      id: '/sluzby/$slug'
      path: '/$slug'
      fullPath: '/sluzby/$slug'
      preLoaderRoute: typeof SluzbySlugRouteImport
      parentRoute: typeof SluzbyRoute
    }
    '/case-studies/$slug': {
      id: '/case-studies/$slug'
      path: '/$slug'
      fullPath: '/case-studies/$slug'
      preLoaderRoute: typeof CaseStudiesSlugRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/$year/$month/$day/$slug': {
      id: '/$year/$month/$day/$slug'
      path: '/$year/$month/$day/$slug'
      fullPath: '/$year/$month/$day/$slug'
      preLoaderRoute: typeof YearMonthDaySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface CaseStudiesRouteChildren {
  CaseStudiesSlugRoute: typeof CaseStudiesSlugRoute
  CaseStudiesIndexRoute: typeof CaseStudiesIndexRoute
}

const CaseStudiesRouteChildren: CaseStudiesRouteChildren = {
  CaseStudiesSlugRoute: CaseStudiesSlugRoute,
  CaseStudiesIndexRoute: CaseStudiesIndexRoute,
}

const CaseStudiesRouteWithChildren = CaseStudiesRoute._addFileChildren(
  CaseStudiesRouteChildren,
)

interface SluzbyRouteChildren {
  SluzbySlugRoute: typeof SluzbySlugRoute
  SluzbyIndexRoute: typeof SluzbyIndexRoute
}

const SluzbyRouteChildren: SluzbyRouteChildren = {
  SluzbySlugRoute: SluzbySlugRoute,
  SluzbyIndexRoute: SluzbyIndexRoute,
}

const SluzbyRouteWithChildren =
  SluzbyRoute._addFileChildren(SluzbyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRouteWithChildren,
  CaseStudiesRoute: CaseStudiesRouteWithChildren,
  MediestetikRoute: MediestetikRoute,
  NavodyZadaniPlatebniMetodyGoogleAdsAOvereniInzerentaRoute:
    NavodyZadaniPlatebniMetodyGoogleAdsAOvereniInzerentaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SluzbyRoute: SluzbyRouteWithChildren,
  YearMonthDaySlugRoute: YearMonthDaySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
